import turtle

window = turtle.Screen()
t = turtle.Pen()
t.speed(10)

for x in range(1):
    t.right(90)
    t.forward(50)
    t.right(90)
    t.forward(50)
    t.right(90)
    t.forward(50)
    t.left(90)
    t.forward(20)
    t.right(120)
    t.forward(90)
    t.right(120)
    t.forward(90)
    t.right(120)
    t.forward(70)
    t.left(90)
    t.penup()
    t.forward(50)
    t.left(90)
    t.forward(25)
    t.left(90)
    t.pendown()
    t.forward(25)
    t.right(90)
    t.forward(8)
    t.right(90)
    t.forward(25)
    t.penup()
    t.goto(-20,-20)
    t.pendown()
    t.right(90)
    t.forward(9)
    t.right(90)
    t.forward(9)
    t.right(90)
    t.forward(9)
    t.right(90)
    t.forward(9)
    t.right(90)
    t.forward(5)
    t.right(90)
    t.forward(9)
    t.right(90)
    t.forward(5)
    t.right(90)
    t.forward(5)
    t.right(90)
    t.forward(9)
    t.penup()
    t.goto(200,200)
